- .github/workflows/ci.yml
- jest.config.js
- package.json
- src/__tests__/getJavaOptions.test.ts
- tsconfig.json
- yarn.lock
This PR adds a basic test infrastructure which is used to test `getJavaOptions`
> Add tests for getJavaOptions

- src/getJavaHome.ts
> Java 11 is 11 not 1.11

- package.json
- src/checkServerVersion.ts
- src/commands/restartServer.ts
- src/detectLaunchConfigurationChanges.ts
- src/index.ts
- src/interfaces/ConfigurationTarget.ts
- src/interfaces/LanguageClient.ts
- src/interfaces/ShowMessage.ts
- src/interfaces/Workspace.ts
- src/interfaces/WorkspaceConfiguration.ts
- yarn.lock
This PR adds more utils taken from the client extensions.
Notably, I've started hitting on some discrepancies between the client APIs, which I'm trying to reconcile at the best of my abilities :P 
I'll leave some comments inline to explain what I mean.
> Add more utils

- package.json
- src/installJava.ts
- src/interfaces/OutputChannel.ts
- yarn.lock
> Add installJava utility

- src/__tests__/getJavaOptions.test.ts
- src/getJavaOptions.ts
Fixes https://github.com/scalameta/metals-languageclient/issues/59
> Make sure we ignore whitespace in java options

- package.json
- src/commands/restartServer.ts
- yarn.lock
Supersedes https://github.com/scalameta/metals-languageclient/pull/75
> Upgrade prettier

- src/index.ts
I may want to actually export them if I want to use them...
> export the interfaces

- package.json
- src/installJava.ts
- yarn.lock
> Update @types/node and specify encoding type

- src/index.ts
- src/interfaces/ClientCommands.ts
- src/interfaces/Extensions.ts
- src/interfaces/MetalsInputBox.ts
- src/interfaces/MetalsQuickPick.ts
- src/interfaces/MetalsSlowTask.ts
- src/interfaces/MetalsStatus.ts
- src/interfaces/ServerCommands.ts
This has been something I've been meaning to work on for quite some time. We still have quite a bit of duplicated code around our extensions. This unifies that. I'll have prs following in coc-metals and the vs code extension as well.
> Migrate over protocols.

- src/interfaces/MetalsInitializationOptions.ts
For clients that do not support decorations inside the text.
Connected to https://github.com/scalameta/metals/pull/2103/files
> Add additional inlineDecorationProvider 

- src/interfaces/ServerCommands.ts
Reliant on what happens with https://github.com/scalameta/metals/pull/2154. The name may change.
> Add in GenerateBspConfig ServerCommand

- src/fetchMetals.ts
Please see issue https://github.com/scalameta/metals-languageclient/issues/219 for details
> Fix issue with http.proxy and IPv6 #219

- src/interfaces/ServerCommands.ts
Command used in https://github.com/scalameta/metals/pull/2290
> Add in copy-worksheet-output command

- src/index.ts
- src/interfaces/DebugDiscoveryParams.ts
As a follow-up to the discovery params added in here: https://github.com/scalameta/metals/pull/2532
> Add in debug discovery params

- .github/workflows/ci.yml
- .github/workflows/release-drafter.yml
- .github/workflows/release.yml
I don't have permissions to actually make the change, but this should be the change that is needed in the code to switch to main for the default branch.
> Switch default branch to main.

- src/interfaces/DebugDiscoveryParams.ts
And I did a typo in the word typo :laughing:
> Fix typ in DebugDiscoveryParams

- package.json
- src/interfaces/Extensions.ts
- src/interfaces/LanguageClient.ts
- src/interfaces/MetalsInputBox.ts
- src/interfaces/MetalsQuickPick.ts
- src/interfaces/MetalsSlowTask.ts
- src/interfaces/MetalsStatus.ts
- src/interfaces/TreeViewProtocol.ts
- yarn.lock
This is very similar to and should close scalameta/metals-languageclient#223 
And it should help going forward for scalameta/metals-feature-requests#202
> Upgrade to `vscode-languageserver-protocol` to v.3.16.0

- LICENSE
Just randomly noticed we don't have a license in here, so adding this in
> Add in LICENSE.

- src/interfaces/ServerCommands.ts
See https://github.com/scalameta/metals/pull/2520
> Add new java file command

- src/interfaces/ServerCommands.ts
See https://github.com/scalameta/metals/pull/3107
> add DecodeFile command

- src/interfaces/MetalsInitializationOptions.ts
See https://github.com/scalameta/metals-vscode/pull/695
> add virtual document config option

- src/interfaces/ServerCommands.ts
> Add GotoPosition server command

- src/__tests__/getJavaHome.test.ts
- src/getJavaHome.ts
Without this change `update-alternatives --config java` doesn't make any
effect on selected jdk becase `locate-java-home` picks the latest one.
> Prefer jdk that goes from `$PATH/java`

- package.json
- src/__tests__/getJavaHome.test.ts
- src/getJavaHome.ts
- yarn.lock
Closes https://github.com/scalameta/metals-vscode/issues/657
> Switch to an active fork of locate-java-home

- src/interfaces/ClientCommands.ts
- src/interfaces/ServerCommands.ts
see https://github.com/scalameta/metals-vscode/pull/660
> display build target info

- src/checkServerVersion.ts
> refactor: delete unnecessary `if` condition

- src/interfaces/ServerCommands.ts
Those added in https://github.com/scalameta/metals/pull/3790.
> Add Scala CLI related commands
