scalameta/metals-languageclient

.github/workflows/ci.yml
src/__tests__/getJavaHome.test.ts
src/__tests__/getJavaOptions.test.ts

We test
- that we can read (in this order) from configuration, JAVA_HOME env, installed Java
- that we prefer JDK over JRE (so that we can index JDK sources), and then we select the most recent version (Java 11 over Java 8, and the most recent security patch)
As explained in the comment, we mock `locate-java-home` since it's an external dependency and we assume it works.

Add tests for getJavaHome

---

src/fetchMetals.ts
src/getJavaConfig.ts
src/getServerOptions.ts
src/index.ts
src/interfaces/ServerOptions.ts

Fetching the Metals jar and computing the launch options for the server is almost identical across coc-metals and VS Code. This PR addresses it.
NOTE: I'm taking baby steps from the implementation leaves, which means this could be deduplicated even further in the future (see for instance `getJavaOptions` which is now an implementation detail we don't expose anymore)

Add utilities to simplify fetching and launching Metals

---

.github/workflows/release.yml
README.md

This pr adds in a simple readme with links to Metals and the two clients utilizing this library.
It also removes github-push-action in favor of just using the checkout action.

add readme and remove github-push-action

---

src/getServerOptions.ts

Relating the this pr in Metals: https://github.com/scalameta/metals/pull/1414
Metals now has the ability to instead of getting this value as a server property, it can be passed in via `experimental` in `ClientCapabilities`.
The following to prs relate to this for the various clients.
https://github.com/scalameta/metals-vscode/pull/207
https://github.com/scalameta/coc-metals/pull/74

remove no longer needed server property

---

src/getServerOptions.ts

`doctorFormat` was removed from the `getServerOption` before, but not the Interface 😬 
This pr removes it from the interface.

remove doctorFormat from GetServerOptions Interface

---

src/detectLaunchConfigurationChanges.ts

This pr adds the ability to pass in extra trigger keys to trigger a server restart. In https://github.com/scalameta/coc-metals/pull/94 I plan to introduce `metals.statusBarEnabled` which will allow a user to either set Metals to use `metals/status` or to default to `showMessages`. This will need to trigger a server restart since the value will be passed to metals via `clientExperimentalCapabilities`.

Add in the ability to use addition restart triggers

---

package.json
yarn.lock

This pr bumps the version of vscode-languageserver-protocol. Current in `coc-metals` we have a resolution that forces `vscode-jsonrpc` to be `^5`. The was originally done because the `coc.nvim` library was lagging behind. However, they are ahead now, so we can update this. Also, they recently changed the way the do installs, which utilizes `npm` when you do a `:CocInstall <url>`. Resolutions doesn't work in `npm` (without another dependency), so it's causing the install to break for people when they are installing via url. This pr will hopefully solve that issue because I can remove the `resolutions` in coc-metals.

bump vscode languageserver protocol dependency

---

src/interfaces/TreeViewProtocol.ts

I'm starting to do some work on TVP in coc-metals, and realized that these are exactly the same in both coc-metals and in the vscode extension, so I figured I'd port them over.

Add in the tree view protocol interfaces

---

src/downloadProgress.ts

Previously, when VS Code would always start a progress notification
window for "Downloading Metals" even when Metals was already cached
locally. Now, the notification window only appears when Metals is
actually being downloaded.
This fixes a small regression in the migration to metals-languageclient.
In the original VS Code implementation, we didn't call `onProgress()`
for stdout https://github.com/scalameta/metals-vscode/commit/051fe19c4e1b8e238d0372cf61b23cf16e3c4e42#diff-45327f86d4438556066de133327f4ca2L635-L637

Don't call `onProgress` for stdout messages.

---

src/__tests__/getJavaOptions.test.ts
src/getJavaOptions.ts

The final classpath is built by looking at the output of the Coursier run fetching metals, so having any extra output results in an invalid classpath ("Error: -classpath requires class path specification").

support "-XX:+PrintCommandLineFlags" in .jvmOpts

---

src/getJavaConfig.ts
src/getServerOptions.ts

This is connected to the issues we've recently had on MacOS. There is a default binary there that looks for JAVA_HOME and if it is not set it will show a pop up. This is especially problematic for Bloop, which tries to use the default java binary and now we will show a pop up whenever the variable is not set and the default binary doesn't point to legitimate java version.
Fixes https://github.com/scalameta/metals/issues/1719
This has two effects:
- we will add JAVA_HOME if it is not set
- we will replace any existing JAVA_HOME with the one used for Metals
We could also skip the second case, but I think it's sensible to set JAVA_HOME to the same value.
I also add @hedefalk  changes from https://github.com/hedefalk/metals-languageclient/commit/ce50e16d7d32a4db560d28e0d3d0502269a82ed8

Set JAVA_HOME to the value we use for Metals 

---

src/getServerOptions.ts
src/index.ts
src/interfaces/MetalsInitializationOptions.ts

Now that https://github.com/scalameta/metals/pull/1903 has been merged, I'm getting started on [stage 2](https://github.com/scalameta/metals/issues/1895) outlined in here. This pr removes the `client` from `baseProperties` and then also adds in a `MetalsInitializationOptions` interface to make setting `initializationOptions` a little less error prone.

Add in the InitializationOptions from Metals

---

src/fetchMetals.ts
src/installJava.ts

Fixes https://github.com/scalameta/metals-vscode/issues/366 and downloading with jabba when the executable has space in path.

Add utf-8 to the process fetching Metals and fix downloading jabba 

---

src/interfaces/ServerCommands.ts

Just a tiny change. I was working on https://github.com/scalameta/metals/issues/2049 and playing around with all the various build server commands and realized this one wasn't in here.

Add in the build-disconnect server command

---

src/interfaces/MetalsInitializationOptions.ts

This option is responsible for letting Metals server know that it can show additional lens in worksheet with the CopyWorksheetOutput client command.

Add copyWorksheetOutputProvider

---

src/fetchMetals.ts

This change allows users to pass a full dependency string, like `com.something:metals_2.12:0.10.5-something-1`, rather than only a Metals version. This allows users to easily use their own fork of Metals if they want to, for example.
Passing a full dependency is optional: versions are still accepted, and are still assumed to correspond to `org.scalameta:metals_2.12`.

Allow users to pass a full dependency string rather than just a version

---

src/__tests__/getJavaHome.test.ts
src/getJavaHome.ts

Should fix scalameta/metals-vscode#821
Instead of assuming that `java` should be a symlink to `java` in javaHome
use the result of `locate-java-home` and select jdk that matches the
`java` from $PATH.

Fix javaHome selection for MacOs

---

src/interfaces/ClientCommands.ts
src/interfaces/ServerCommands.ts

See https://github.com/scalameta/metals-vscode/pull/893
This also removes the client command - I think I added that by mistake - should have just been server command

Change displayBuildTarget to listBuildTargets

---

src/checkServerVersion.ts
src/detectLaunchConfigurationChanges.ts
src/getJavaConfig.ts
src/interfaces/ClientCommands.ts
src/interfaces/UserConfiguration.ts

This can be found https://github.com/coursier/coursier/blob/master/modules/paths/src/main/java/coursier/paths/Mirror.java#L26
Tested  it out and seems to work (URLs go replaced by my string)
Will create VS Code PR soon.

Add mirror env variable when set by the user

---

src/__tests__/fetchMetals.test.ts
src/fetchMetals.ts

This PR is the same as https://github.com/scalameta/nvim-metals/pull/346
(As of https://github.com/scalameta/metals/pull/3631 we now have 2.13 artifacts instead of 2.12).
Confirmed we can download `publishLocal`ed metals server `0.11.13-SNAPSHOT` with this
- `yarn link` in this repo
- `yarn link "metals-languageclient"` in `metals-vscode`
- Run extension by `F5`

feat: support new 2.13 artifacts

---

.github/dependabot.yml

see: https://github.com/scalameta/metals-languageclient/pull/405#issuecomment-1075375822

Ignore dependabot to upgrade node-fetch to v3

---

src/util.ts

The `pipeable.pipe` is deprecated in fp-ts `2.10.0`
> https://github.com/gcanti/fp-ts/commit/cf2eb5f522d7f7d59686ceb53000545ee3cfed69#diff-525b26146709ecb0afacc1b32b888c93d30565ae689cb87349c329ab34e9520cR1563

refactor: use `function.pipe` instead of `pipeable.pipe`

---

src/installJava.ts

As is the title.
I selected the `openjdk@1.17`. Is this a no problem?
```sh
$ jabba ls-remote | grep 17
amazon-corretto@1.17.0-0.35.1
openjdk@1.17.0
openjdk-ri@1.17.0
zulu@1.17.0-0
zulu@1.8.172
zulu@1.7.171
```
Thank you :)

feat: add `openjdk@1.17` to type of JavaVersion

---

.github/workflows/release.yml

It's easier to create release from GH than pushing a tag and then creating GH release

ci: trigger release workflow when GH release is created

---

src/interfaces/LanguageClient.ts

vscode-languageclient to 8.0.1 modified the signatures of the
LanguageClient and it doesn't match with the LanguageClient interface
defined in this package.
see: https://github.com/scalameta/metals-vscode/pull/983
Not sure why these abstract members were needed: looks like
LanguageClient requires only two members, and others are unused.
Removing other unused abstract members from `LanguageClient` in metals-language-client
so that it matches the signature of `LanguageClient` from
vscode-languageclient.

refactor: Remove unused abstract members from LanguageClient

---

.github/workflows/release.yml

see: https://github.com/scalameta/metals-languageclient/runs/6752667431?check_suite_focus=true
```
error vscode-jsonrpc@8.0.1: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "10.24.1"
```

Update node version of release workflow
